description = "Execute spec tasks using TDD methodology"

prompt = """
# Execute Spec Tasks with TDD

Execute implementation tasks from spec using Kent Beck's Test-Driven Development methodology.

## Arguments: {{args}}

## Current Specs
Available specs: !{bash -c 'ls {{KIRO_DIR}}/specs/ 2>/dev/null || echo "No specs found"'}

## Instructions

### Help Mode (--help)
If arguments contain "--help", show usage:
```
/kiro:spec-impl <feature-name> <task-numbers>

Examples:
  /kiro:spec-impl auth-system 1.1            # Execute task 1.1
  /kiro:spec-impl auth-system 1,2,3          # Execute tasks 1, 2, 3
  /kiro:spec-impl auth-system --all          # Execute all pending tasks
```

### Pre-Execution Validation
Feature name: **{{args}}** (first argument will be parsed as feature name)

Validate required files exist:
- Requirements: Check if {{KIRO_DIR}}/specs/[FEATURE]/requirements.md exists
- Design: Check if {{KIRO_DIR}}/specs/[FEATURE]/design.md exists  
- Tasks: Check if {{KIRO_DIR}}/specs/[FEATURE]/tasks.md exists
- Metadata: Check if {{KIRO_DIR}}/specs/[FEATURE]/spec.json exists

**Note**: Replace [FEATURE] with the first argument from {{args}}

### Context Loading
**Load all required content before execution:**

**Core Steering:**
- Structure: @{{KIRO_DIR}}/steering/structure.md
- Tech Stack: @{{KIRO_DIR}}/steering/tech.md  
- Product: @{{KIRO_DIR}}/steering/product.md

**Custom Steering:**
Additional files: List additional steering files in {{KIRO_DIR}}/steering/

**Spec Documents:**
Feature directory: **{{args}}** (first argument)
- Requirements: @{{KIRO_DIR}}/specs/[FEATURE]/requirements.md
- Design: @{{KIRO_DIR}}/specs/[FEATURE]/design.md
- Tasks: @{{KIRO_DIR}}/specs/[FEATURE]/tasks.md

**Note**: [FEATURE] will be replaced with actual feature name during execution

### Task Execution
1. **Parse feature name and task numbers** from arguments
2. **Load all context** (steering + spec documents)
3. **Extract checkboxes** from tasks.md for the specified feature
4. **Execute each checkbox** using TDD methodology directly

### For Each Task Checkbox
Execute using TDD methodology directly:

**Implementation Steps:**
1. **Load Project Context** (read these files first):
   - Structure: {{KIRO_DIR}}/steering/structure.md  
   - Tech Stack: {{KIRO_DIR}}/steering/tech.md
   - Product: {{KIRO_DIR}}/steering/product.md
   - Custom steering files: List additional steering files in {{KIRO_DIR}}/steering/
   - Spec Metadata: {{KIRO_DIR}}/specs/[FEATURE]/spec.json
   - Requirements: {{KIRO_DIR}}/specs/[FEATURE]/requirements.md
   - Design: {{KIRO_DIR}}/specs/[FEATURE]/design.md
   - All Tasks: {{KIRO_DIR}}/specs/[FEATURE]/tasks.md

2. **TDD Implementation** for each specific task:
   - **RED**: Write failing tests first
   - **GREEN**: Write minimal code to pass tests
   - **REFACTOR**: Clean up and improve code structure

3. **Task Completion**:
   - Verify all tests pass
   - Update checkbox from `- [ ]` to `- [x]` in {{KIRO_DIR}}/specs/[FEATURE]/tasks.md
   - Ensure no regressions in existing tests

**For each task:**
- Extract exact checkbox content from tasks.md
- Follow Kent Beck's TDD methodology strictly
- Implement only the specific task requirements
- Maintain code quality and test coverage

## Implementation Logic

1. **Parse Arguments**:
   - Feature name: First argument
   - Task numbers: Second argument (support: "1", "1,2,3", "--all")

2. **Validate**:
   - Spec directory exists
   - Required files (requirements.md, design.md, tasks.md, spec.json) exist
   - Spec is approved for implementation

3. **Execute**:
   - **Load all file contents** into memory first
   - **Build complete context** for implementation
   - **Execute each task sequentially** using TDD methodology
   - Each task implementation receives complete project knowledge

## Error Handling

- Spec not found: Run /kiro:spec-init first
- Not approved: Complete spec workflow first
- Task failure: Keep checkbox unchecked, show error

## Success Metrics

- All selected checkboxes marked [x] in tasks.md
- Tests pass
- No regressions
"""
